### ISSUE TITLE
Error reporting crashes at android

### ISSUE THREAD

**Issue by zwerg44** [doochik/react-native-appmetrica#12]
version: 0.1.1
os: android 6.0.1

Function `reportError` crashes.

I tried both:
- passing second `reason` argument to reportError
- passing only `error` string without `reason`

Javascript code always passes 2 arguments to its native bridge [link](https://github.com/doochik/react-native-appmetrica/blob/f35de9a958992bf949cd8ecb39539b90ea17013d/index.js#L30)

In the android bridge there is no second argument [link](https://github.com/doochik/react-native-appmetrica/blob/f35de9a958992bf949cd8ecb39539b90ea17013d/android/src/main/java/com/doochik/RNAppMetrica/AppMetricaModule.java#L45)

That produces crash:
`com.facebook.react.bridge.NativeArgumentsParseException: AppMetrica.reportError got 2 arguments, expected 1 at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:355) at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162) at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) at android.os.Handler.handleCallback(Handler.java:739) at android.os.Handler.dispatchMessage(Handler.java:95) at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) at android.os.Looper.loop(Looper.java:148) at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194) at java.lang.Thread.run(Thread.java:818) `

**Comment by zwerg44** [comment]
looks like there is fix in this fork
https://github.com/10levels/react-native-appmetrica/commit/0de3bc30c221eb0c1001946d3e5a7473e88caefc
