### ISSUE TITLE
null is not an object (evaluating 'AppMetrica.activate')

### ISSUE THREAD

**Issue by AndreyMashukov** [doochik/react-native-appmetrica#56]
TypeError: null is not an object (evaluating 'AppMetrica.activate')
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0

{
  "main": "index.js",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "expo start --dev-client",
    "test": "jest"
  },
  "dependencies": {
    "@eva-design/eva": "^2.1.1",
    "@react-native-async-storage/async-storage": "^1.13.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/bottom-tabs": "^5.11.11",
    "@react-navigation/material-top-tabs": "^5.3.15",
    "@react-navigation/native": "^5.9.4",
    "@ui-kitten/components": "^5.1.0",
    "axios": "^0.24.0",
    "class-transformer": "^0.5.1",
    "expo": "^41.0.0",
    "expo-splash-screen": "~0.10.2",
    "expo-status-bar": "~1.0.4",
    "expo-updates": "~0.5.4",
    "js-sha256": "^0.9.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "~0.63.4",
    "react-native-appmetrica": "^2.0.0",
    "react-native-elements": "^3.4.1",
    "react-native-pager-view": "5.0.12",
    "react-native-reanimated": "~2.1.0",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens": "~3.0.0",
    "react-native-svg": "12.1.0",
    "react-native-tab-view": "^3.0.1",
    "react-native-unimodules": "~0.13.3",
    "react-native-web": "~0.13.12",
    "react-reactive-form": "^1.0.32",
    "react-redux": "^7.2.6",
    "redux": "^4.1.2",
    "reflect-metadata": "^0.1.13"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "@types/react": "~16.9.35",
    "@types/react-native": "~0.63.2",
    "babel-preset-expo": "8.3.0",
    "jest-expo": "^41.0.0",
    "typescript": "~4.0.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true,
  "name": "app",
  "version": "1.0.0"
}

**Comment by ghost** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 15454726. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp11.01.2022, 13:11, "Andrew Mashukov" ***@***.***>:
TypeError: null is not an object (evaluating 'AppMetrica.activate')
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
Invariant Violation: "main" has not been registered. This can happen if:

Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
A module failed to load due to an error and AppRegistry.registerComponent wasn't called.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0

{
"main": "index.js",
"scripts": {
"android": "react-native run-android",
"ios": "react-native run-ios",
"web": "expo start --web",
"start": "expo start --dev-client",
"test": "jest"
},
"dependencies": {
***@***.***/eva": "^2.1.1",
***@***.***/async-storage": "^1.13.0",
***@***.***/masked-view": "0.1.10",
***@***.***/bottom-tabs": "^5.11.11",
***@***.***/material-top-tabs": "^5.3.15",
***@***.***/native": "^5.9.4",
***@***.***/components": "^5.1.0",
"axios": "^0.24.0",
"class-transformer": "^0.5.1",
"expo": "^41.0.0",
"expo-splash-screen": "~0.10.2",
"expo-status-bar": "~1.0.4",
"expo-updates": "~0.5.4",
"js-sha256": "^0.9.0",
"react": "16.13.1",
"react-dom": "16.13.1",
"react-native": "~0.63.4",
"react-native-appmetrica": "^2.0.0",
"react-native-elements": "^3.4.1",
"react-native-pager-view": "5.0.12",
"react-native-reanimated": "~2.1.0",
"react-native-safe-area-context": "3.2.0",
"react-native-screens": "~3.0.0",
"react-native-svg": "12.1.0",
"react-native-tab-view": "^3.0.1",
"react-native-unimodules": "~0.13.3",
"react-native-web": "~0.13.12",
"react-reactive-form": "^1.0.32",
"react-redux": "^7.2.6",
"redux": "^4.1.2",
"reflect-metadata": "^0.1.13"
},
"devDependencies": {
***@***.***/core": "~7.9.0",
***@***.***/react": "~16.9.35",
***@***.***/react-native": "~0.63.2",
"babel-preset-expo": "8.3.0",
"jest-expo": "^41.0.0",
"typescript": "~4.0.0"
},
"jest": {
"preset": "react-native"
},
"private": true,
"name": "app",
"version": "1.0.0"
}

**Comment by AndreyMashukov** [comment]
problem is reproduced only on Expo, with raw react-native it works fine
